### ISSUE TITLE
(Feat)Create Hero page

### ISSUE THREAD

**Issue by Isaacvf-dev** [daniel-francelino/ecomerce-web-mart#1]
The hero page should be created according to Figma layout 'HomePage 2'
- Desktop and Mobile version

![image](https://github.com/lostcode-dev/ecomerce-web-mart/assets/123469000/97aced04-3b87-4762-ba77-4274ef5f33bb)
![image](https://github.com/lostcode-dev/ecomerce-web-mart/assets/123469000/613b654b-1b11-420e-94d5-0aa6d811ad83)

**Comment by Saulbez** [comment]
Testing
